// models/Audit.js
// This file defines what an "Audit" document looks like in MongoDB.
// Think of this as a blueprint / template for every audit we save.

import mongoose from "mongoose";

// -------------------------------------------------------------------
// Sub-schema: A single tool the user entered
// e.g. { name: "cursor", plan: "pro", monthlySpend: 40, seats: 2 }
// -------------------------------------------------------------------
const ToolSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: [true, "Tool name is required"],
      trim: true,
      // trim removes accidental leading/trailing spaces
    },
    plan: {
      type: String,
      required: [true, "Plan is required"],
      trim: true,
    },
    monthlySpend: {
      type: Number,
      required: [true, "Monthly spend is required"],
      min: [0, "Monthly spend cannot be negative"],
    },
    seats: {
      type: Number,
      required: [true, "Number of seats is required"],
      min: [1, "Must have at least 1 seat"],
    },
  },
  { _id: false }
  // _id: false means Mongoose won't create a separate _id for each tool object
  // This keeps the data cleaner since tools are sub-documents, not top-level docs
);

// -------------------------------------------------------------------
// Sub-schema: A single result item after audit engine runs
// We keep this as a placeholder for now — audit engine comes in Day 3
// e.g. { tool: "cursor", currentSpend: 40, recommendation: "...", savings: 20, reason: "..." }
// -------------------------------------------------------------------
const ResultSchema = new mongoose.Schema(
  {
    tool: { type: String },
    currentSpend: { type: Number },
    recommendedAction: { type: String },
    savings: { type: Number },
    reason: { type: String },
  },
  { _id: false }
);

// -------------------------------------------------------------------
// Main Audit Schema
// -------------------------------------------------------------------
const AuditSchema = new mongoose.Schema(
  {
    // auditId is a short unique string we generate ourselves (like "abc123xyz")
    // This is what we use in the shareable URL: /audit/abc123xyz
    // It is different from MongoDB's default _id
    auditId: {
      type: String,
      required: true,
      unique: true, // no two audits can have the same auditId
      trim: true,
    },

    // Array of tools the user entered
    tools: {
      type: [ToolSchema],
      required: [true, "At least one tool is required"],
      validate: {
        // Custom validator: tools array must not be empty
        validator: (val) => val.length > 0,
        message: "Please add at least one tool",
      },
    },

    // Total number of people on the team (not just tool seats)
    teamSize: {
      type: Number,
      required: [true, "Team size is required"],
      min: [1, "Team size must be at least 1"],
    },

    // What does the team primarily use AI for?
    useCase: {
      type: String,
      required: [true, "Use case is required"],
      enum: {
        values: ["coding", "writing", "data", "research", "mixed"],
        message: "Use case must be one of: coding, writing, data, research, mixed",
      },
    },

    // Filled in after audit engine runs (Day 3)
    // Default is empty array — placeholder for now
    results: {
      type: [ResultSchema],
      default: [],
    },

    // Calculated totals — filled after audit engine runs
    totalMonthlySavings: {
      type: Number,
      default: 0,
    },

    totalAnnualSavings: {
      type: Number,
      default: 0,
    },

    // 100-word summary generated by Claude API (Day 4)
    // Empty string by default until AI generates it
    aiSummary: {
      type: String,
      default: "",
      trim: true,
    },

    // true if totalMonthlySavings > 500
    // Used to decide whether to show "Talk to Credex" CTA
    isHighValue: {
      type: Boolean,
      default: false,
    },
  },
  {
    // timestamps: true automatically adds "createdAt" and "updatedAt" fields
    // You don't need to define them manually
    timestamps: true,
  }
);

// Export the model so controllers can use it
// mongoose.model("Audit", AuditSchema) creates a collection called "audits" in MongoDB
const Audit = mongoose.model("Audit", AuditSchema);
export default Audit;